swagger: '2.0'
info:
  version: '1.0'
  title: TP2--TestApi
  contact: {}
host: localhost:8085
basePath: /api
schemes:
- http
consumes:
- application/json
produces:
- application/json
paths:
  /comercios:
    get:
      summary: Buscar comercios ceranos
      tags:
      - Misc
      operationId: Buscarcomerciosceranos
      deprecated: false
      produces:
      - application/json
      parameters:
      - name: cuil
        in: query
        required: true
        type: integer
        format: int64
        description: ''
      - name: maxDistance
        in: query
        required: true
        type: number
        format: double
        description: ''
      responses:
        200:
          description: ''
          headers: {}
  /facturas:
    post:
      summary: Generar factura
      tags:
      - Misc
      operationId: Generarfactura
      deprecated: false
      produces:
      - application/json
      parameters:
      - name: Body
        in: body
        required: true
        description: ''
        schema:
          $ref: '#/definitions/GenerarfacturaRequest'
      responses:
        200:
          description: ''
          headers: {}
definitions:
  GenerarfacturaRequest:
    title: GenerarfacturaRequest
    example:
      cuil: 784784
    type: object
    properties:
      cuil:
        type: string
    required:
    - cuil
tags:
- name: Misc
  description: ''
